### ISSUE TITLE
Update Azure Spring Cloud dependency with new SDK for Steeltoe 3.0

### ISSUE THREAD

**Issue by jkonicki** [steeltoeoss-incubator/Steeltoe.Initializr.Configuration#37]
Steeltoe3ForASC.csproj Line 8
	Add our package reference to 2.0.0-preview.1
Program.cs Line 2
	Add `using Microsoft.Azure.SpringCloud.Client;`
Program.cs Line 16
	Add `.UseAzureSpringCloudService()` (must be added before any other steeltoe configurations to inject our certificates)

Sample is attached:
[Steeltoe3ForASCHelloWorld.zip](https://github.com/SteeltoeOSS/InitializrConfig/files/5563084/Steeltoe3ForASCHelloWorld.zip)

**Comment by ccheetham** [comment]
Sample using staging server:
```
$ http http://start-staging.steeltoe.io/api/project name==MyAzureProject dependencies==azure-spring-cloud -d
$ unzip MyAzureProject.zip
$ grep Azure MyAzureProject/MyAzureProject.csproj
    <PackageReference Include="Microsoft.Azure.SpringCloud.Client" Version="2.0.0-preview.1" />
```
