### ISSUE TITLE
Spring Cloud Config Server adds incorrect dependency

### ISSUE THREAD

**Issue by ccheetham** [steeltoeoss-incubator/Steeltoe.Initializr.Configuration#41]
@macsux commented on [Thu Nov 19 2020](https://github.com/SteeltoeOSS/Initializr/issues/134)

Adding `Spring Cloud Config Server` adds `    <PackageReference Include="Steeltoe.Extensions.Configuration.config-serverCore" Version="3.0.1" />` which is invalid package

**Comment by jkonicki** [comment]
https://github.com/SteeltoeOSS/InitializrConfig/commit/a3a721c78ee76b1e0da1dd17bf6007b51e2328ab
