### ISSUE TITLE
Adding MySQL EFCore does not configure Startup file

### ISSUE THREAD

**Issue by ccheetham** [steeltoeoss-incubator/Steeltoe.Initializr.Configuration#42]
@macsux commented on [Thu Nov 19 2020](https://github.com/SteeltoeOSS/Initializr/issues/135)

Adding MySQL EFCore does not configure Startup file to register it into DI container

**Comment by jkonicki** [comment]
Commit - https://github.com/SteeltoeOSS/InitializrConfig/commit/0ae0ca63a1b942e8e5f83e188de44b869f8a3e04
