### ISSUE TITLE
Newtonsoft.Json should not be added by default to the template

### ISSUE THREAD

**Issue by ccheetham** [steeltoeoss-incubator/Steeltoe.Initializr.Configuration#44]
@macsux commented on [Thu Nov 19 2020](https://github.com/SteeltoeOSS/Initializr/issues/137)

There's no reason to have Newtonsoft.Json as part of default template when ASP.NET Core brings it's own, lighter engine. This should be an optional dependency.

**Comment by jkonicki** [comment]
Commit - https://github.com/SteeltoeOSS/InitializrConfig/commit/3489410edd09f3054d95c32c647572ff4bd0ff76
