### ISSUE TITLE
Scope validation for DI is disabled by default

### ISSUE THREAD

**Issue by ccheetham** [steeltoeoss-incubator/Steeltoe.Initializr.Configuration#45]
@macsux commented on [Thu Nov 19 2020](https://github.com/SteeltoeOSS/Initializr/issues/138)

The template is disabling DI scope validation by default which is not something most people want

`.UseDefaultServiceProvider(configure => configure.ValidateScopes = false)`

**Comment by jkonicki** [comment]
https://github.com/SteeltoeOSS/InitializrConfig/commit/be39e31852f264684bf5f98d826e3bb1a1bf108a
