### ISSUE TITLE
Adding Actuators are CloudFoundry dependent

### ISSUE THREAD

**Issue by ccheetham** [steeltoeoss-incubator/Steeltoe.Initializr.Configuration#46]
@macsux commented on [Thu Nov 19 2020](https://github.com/SteeltoeOSS/Initializr/issues/139)

Adding actuators makes them CloudFoundry dependent. This should be a generic version, and a separate CF specific actuator dependency introduced.

**Comment by jkonicki** [comment]
Currently the `Actuators` dependency ties it to Cloud Foundry.  This should be renamed to  `Actuators in CloudFoundry` and another dependency should be created and added for just `Actuators`
