### ISSUE TITLE
Adding Actuators brings in Serilog Dynamic logger

### ISSUE THREAD

**Issue by ccheetham** [steeltoeoss-incubator/Steeltoe.Initializr.Configuration#47]
@macsux commented on [Thu Nov 19 2020](https://github.com/SteeltoeOSS/Initializr/issues/140)

Actuators should not bring serilog dynamic logger, only core dynamic logger.

**Comment by jkonicki** [comment]
https://github.com/SteeltoeOSS/InitializrConfig/commit/e12539d74b4c787bdb7d3e6f24614a74c791cd33
