### ISSUE TITLE
Rename Circuit Breaker to Hystrix Circuit Breaker

### ISSUE THREAD

**Issue by ccheetham** [steeltoeoss-incubator/Steeltoe.Initializr.Configuration#48]
@macsux commented on [Thu Nov 19 2020](https://github.com/SteeltoeOSS/Initializr/issues/141)

There are multiple libraries that add circuit breaker pattern to code, and TBH Polly is significantly more popular and easier to use then Steeltoe Hystrix version. This will help differentiate the two and offer both.

**Comment by jkonicki** [comment]
Update the description to `Netflix Hystrix Circuit Breaker`
