### ISSUE TITLE
Azure Spring Cloud versioning is incorrect in staging area

### ISSUE THREAD

**Issue by jkonicki** [steeltoeoss-incubator/Steeltoe.Initializr.Configuration#58]
Azure Spring Cloud version should be like this

* All require .NETCore 3.x+
* Azure SDK 1.0.x should be used with Steeltoe 2.x only
* Azure SDK 2.x should be used with Steeltoe 3.x+

Currently, they are all using Azure SDK 2.x, which will not work.

**Comment by jkonicki** [comment]
Successor to #37

**Comment by ccheetham** [comment]
The issue turns out to the Initializr web not honoring selected Steeltoe version.
If project is generated using the API, the expected Azure SDK version is configured.

https://github.com/SteeltoeOSS/InitializrWeb/issues/66
