### ISSUE TITLE
Add Steeltoe Stream dependency template 

### ISSUE THREAD

**Issue by jkonicki** [steeltoeoss-incubator/Steeltoe.Initializr.Configuration#92]
The Steeltoe Stream w/ RabbitMQ feature will be available in the Steeltoe 3.1.0 release.  We need to add a new dependency template to the list that is specific to 3.1.0.

**Comment by ccheetham** [comment]
Sample code:
https://github.com/SteeltoeOSS/Samples/tree/main/Stream/Basic
